// GENERATED by scripts/embed-fixtures.mjs from fixtures/*.json. Do not edit.
//
// The JSON directory is the source of truth; this is the copy the suite can
// import where there is no filesystem, such as a renderer's browser tests. The
// `readonly Fixture[]` annotation is load-bearing: it makes the package's
// typecheck a validator for every shipped case.
import type { Fixture } from './types.js'

export const builtinFixtures: readonly Fixture[] = [
  {
    name: 'a calculated field recomputes from its inputs and is never typed into',
    description: 'A calculated value is derived on every change to anything it reads, not on blur and not on submit, so what a person sees is never briefly wrong. It is read-only in the accessible tree, which is how a renderer stops someone typing into a value the engine will overwrite. It travels in the payload so that a consumer reads the same number the person saw rather than recomputing it and disagreeing.',
    tags: [
      'calculation',
    ],
    schema: {
      specVersion: '0',
      id: 'quote',
      title: 'Request a quote',
      model: {
        fields: [
          {
            key: 'quantity',
            type: 'number',
            label: 'Quantity',
            required: true,
          },
          {
            key: 'unitPrice',
            type: 'number',
            label: 'Unit price',
            required: true,
          },
          {
            key: 'total',
            type: 'number',
            label: 'Total',
            readOnly: true,
            calculate: 'quantity * unitPrice',
          },
        ],
      },
    },
    steps: [
      {
        set: {
          quantity: 3,
          unitPrice: 5,
        },
      },
      {
        expectValue: {
          total: 15,
        },
      },
      {
        set: {
          quantity: 4,
        },
      },
      {
        expectValue: {
          total: 20,
        },
      },
      {
        expectVisible: [
          'total',
        ],
      },
      {
        expectNoErrors: true,
      },
      {
        submit: true,
      },
      {
        expectSubmit: {
          status: 'accepted',
          data: {
            quantity: 4,
            unitPrice: 5,
            total: 20,
          },
        },
      },
    ],
  },
  {
    name: 'a hidden value is dropped only when the field asks for it',
    description: 'Retaining by default is the safe direction: someone who ticks a box back on expects to find what they typed. `clearOnHide` is the opt-in for the case where keeping it would submit an answer to a question that was withdrawn. A cleared field leaves no key in the payload at all, rather than a null every consumer then has to special-case.',
    tags: [
      'visibility',
      'data',
    ],
    schema: {
      specVersion: '0',
      id: 'order',
      title: 'Place an order',
      model: {
        fields: [
          {
            key: 'hasDetails',
            type: 'checkbox',
            label: 'Add delivery details',
          },
          {
            key: 'notes',
            type: 'textarea',
            label: 'Delivery notes',
            visibleWhen: 'hasDetails',
            clearOnHide: true,
          },
          {
            key: 'reference',
            type: 'text',
            label: 'Order reference',
            visibleWhen: 'hasDetails',
            clearOnHide: false,
          },
        ],
      },
    },
    steps: [
      {
        set: {
          hasDetails: true,
        },
      },
      {
        expectVisible: [
          'notes',
          'reference',
        ],
      },
      {
        set: {
          notes: 'Call before noon',
          reference: 'REF-42',
        },
      },
      {
        set: {
          hasDetails: false,
        },
      },
      {
        expectHidden: [
          'notes',
          'reference',
        ],
      },
      {
        submit: true,
      },
      {
        expectSubmit: {
          status: 'accepted',
          data: {
            hasDetails: false,
            reference: 'REF-42',
          },
        },
      },
      {
        set: {
          hasDetails: true,
        },
      },
      {
        expectValue: {
          notes: '',
          reference: 'REF-42',
        },
      },
    ],
  },
  {
    name: 'conditional visibility follows country',
    description: 'A field nobody can see is a field nobody can fix, so a hidden field is not validated: `state` is required and invisible in Switzerland, and must not block submit. Switching country moves the requirement rather than adding to it.',
    tags: [
      'visibility',
      'validation',
    ],
    schema: {
      specVersion: '0',
      id: 'address',
      title: 'Where do you live?',
      model: {
        fields: [
          {
            key: 'country',
            type: 'select',
            label: 'Country',
            required: true,
            options: [
              {
                value: 'CH',
                label: 'Switzerland',
              },
              {
                value: 'US',
                label: 'United States',
              },
            ],
          },
          {
            key: 'canton',
            type: 'text',
            label: 'Canton',
            required: true,
            visibleWhen: 'country == \'CH\'',
          },
          {
            key: 'state',
            type: 'text',
            label: 'State',
            required: true,
            visibleWhen: 'country == \'US\'',
          },
        ],
      },
    },
    steps: [
      {
        expectHidden: [
          'canton',
          'state',
        ],
      },
      {
        set: {
          country: 'CH',
        },
      },
      {
        expectVisible: [
          'canton',
        ],
      },
      {
        expectHidden: [
          'state',
        ],
      },
      {
        submit: true,
      },
      {
        expectSubmit: {
          status: 'rejected',
        },
      },
      {
        expectErrors: {
          canton: [
            'required',
          ],
          state: [],
        },
      },
      {
        set: {
          country: 'US',
        },
      },
      {
        expectVisible: [
          'state',
        ],
      },
      {
        expectHidden: [
          'canton',
        ],
      },
      {
        expectErrors: {
          canton: [],
        },
      },
      {
        set: {
          state: 'CA',
        },
      },
      {
        submit: true,
      },
      {
        expectSubmit: {
          status: 'accepted',
        },
      },
    ],
  },
  {
    name: 'a repeating group validates each item and re-indexes when one is removed',
    description: 'Removing an item is not the same as clearing it: everything after it moves down by one, and so do its values and its messages. A message left behind on contacts[1] after contacts[0] was removed points at a field that is no longer on screen, which is the classic repeater bug and the reason this case pins the indices so hard.',
    tags: [
      'repeater',
      'validation',
    ],
    schema: {
      specVersion: '0',
      id: 'team',
      title: 'Who should we contact?',
      model: {
        fields: [
          {
            key: 'contacts',
            type: 'repeater',
            label: 'Contacts',
            minItems: 1,
            addLabel: 'Add contact',
            removeLabel: 'Remove contact',
            children: [
              {
                key: 'name',
                type: 'text',
                label: 'Name',
                required: true,
              },
              {
                key: 'email',
                type: 'text',
                label: 'Email',
                required: true,
              },
            ],
          },
        ],
      },
    },
    steps: [
      {
        expectVisible: [
          'contacts[0].name',
          'contacts[0].email',
        ],
      },
      {
        addItem: 'contacts',
      },
      {
        expectVisible: [
          'contacts[1].name',
          'contacts[1].email',
        ],
      },
      {
        set: {
          'contacts[1].name': 'Ada',
        },
      },
      {
        submit: true,
      },
      {
        expectSubmit: {
          status: 'rejected',
        },
      },
      {
        expectErrors: {
          'contacts[0].name': [
            'required',
          ],
          'contacts[0].email': [
            'required',
          ],
          'contacts[1].name': [],
          'contacts[1].email': [
            'required',
          ],
        },
      },
      {
        removeItem: {
          path: 'contacts',
          index: 0,
        },
      },
      {
        expectValue: {
          'contacts[0].name': 'Ada',
        },
      },
      {
        expectErrors: {
          'contacts[0].name': [],
          'contacts[0].email': [
            'required',
          ],
        },
      },
      {
        expectNoErrors: [
          'contacts[1].name',
          'contacts[1].email',
        ],
      },
      {
        set: {
          'contacts[0].email': 'ada@example.com',
        },
      },
      {
        submit: true,
      },
      {
        expectSubmit: {
          status: 'accepted',
          data: {
            contacts: [
              {
                name: 'Ada',
                email: 'ada@example.com',
              },
            ],
          },
        },
      },
    ],
  },
  {
    name: 'a required field blocks submit until it has a value',
    description: 'Messages appear when the form is submitted, not while someone is still filling it in for the first time. Once a field has been told it is wrong, it re-validates as it is edited, so the message disappears the moment the value is good rather than at the next submit.',
    tags: [
      'validation',
    ],
    schema: {
      specVersion: '0',
      id: 'contact',
      title: 'Contact us',
      model: {
        fields: [
          {
            key: 'email',
            type: 'text',
            label: 'Email',
            required: true,
          },
          {
            key: 'message',
            type: 'textarea',
            label: 'Message',
          },
        ],
      },
    },
    steps: [
      {
        expectNoErrors: true,
      },
      {
        submit: true,
      },
      {
        expectSubmit: {
          status: 'rejected',
        },
      },
      {
        expectErrors: {
          email: [
            'required',
          ],
          message: [],
        },
      },
      {
        set: {
          email: 'ada@example.com',
        },
      },
      {
        expectNoErrors: true,
      },
      {
        submit: true,
      },
      {
        expectSubmit: {
          status: 'accepted',
        },
      },
    ],
  },
  {
    name: 'a wizard validates the current page on next and the whole form on submit',
    description: 'Next may only look at the page a person is on: validating pages they have not reached yet would show them errors for questions nobody has asked them. Submit must look at everything, because an answer on a later page can make a field on an earlier one required, and it must take them to the first page that has a problem rather than leaving them on a clean review page staring at a rejection. Pages are presentation: they own no data, so the payload is flat and moving a field between pages is not a data migration.',
    tags: [
      'wizard',
      'validation',
    ],
    schema: {
      specVersion: '0',
      id: 'signup',
      title: 'Open an account',
      model: {
        fields: [
          {
            key: 'details',
            type: 'page',
            label: 'Your details',
            children: [
              {
                key: 'firstName',
                type: 'text',
                label: 'First name',
                required: true,
              },
              {
                key: 'lastName',
                type: 'text',
                label: 'Last name',
                required: true,
              },
              {
                key: 'company',
                type: 'text',
                label: 'Company',
                requiredWhen: 'invoiceToCompany',
              },
            ],
          },
          {
            key: 'address',
            type: 'page',
            label: 'Address',
            children: [
              {
                key: 'street',
                type: 'text',
                label: 'Street',
                required: true,
              },
              {
                key: 'city',
                type: 'text',
                label: 'City',
                required: true,
              },
              {
                key: 'invoiceToCompany',
                type: 'checkbox',
                label: 'Invoice my company',
              },
            ],
          },
          {
            key: 'review',
            type: 'page',
            label: 'Review',
            children: [
              {
                key: 'confirm',
                type: 'checkbox',
                label: 'Everything above is correct',
                required: true,
              },
            ],
          },
        ],
      },
    },
    steps: [
      {
        expectPage: 'details',
      },
      {
        expectVisible: [
          'firstName',
          'lastName',
          'company',
        ],
      },
      {
        expectHidden: [
          'street',
          'city',
          'confirm',
        ],
      },
      {
        next: true,
      },
      {
        expectPage: 'details',
      },
      {
        expectErrors: {
          firstName: [
            'required',
          ],
          lastName: [
            'required',
          ],
          street: [],
          city: [],
          confirm: [],
        },
      },
      {
        set: {
          firstName: 'Ada',
          lastName: 'Lovelace',
        },
      },
      {
        next: true,
      },
      {
        expectPage: 'address',
      },
      {
        expectNoErrors: true,
      },
      {
        back: true,
      },
      {
        expectPage: 'details',
      },
      {
        expectValue: {
          firstName: 'Ada',
        },
      },
      {
        next: true,
      },
      {
        expectPage: 'address',
      },
      {
        next: true,
      },
      {
        expectPage: 'address',
      },
      {
        expectErrors: {
          street: [
            'required',
          ],
          city: [
            'required',
          ],
          confirm: [],
        },
      },
      {
        set: {
          street: 'Rue de la Gare 1',
          city: 'Lausanne',
          invoiceToCompany: true,
        },
      },
      {
        next: true,
      },
      {
        expectPage: 'review',
      },
      {
        set: {
          confirm: true,
        },
      },
      {
        submit: true,
      },
      {
        expectSubmit: {
          status: 'rejected',
        },
      },
      {
        expectErrors: {
          company: [
            'required',
          ],
        },
      },
      {
        expectPage: 'details',
      },
      {
        set: {
          company: 'Analytical Engines',
        },
      },
      {
        next: true,
      },
      {
        next: true,
      },
      {
        expectPage: 'review',
      },
      {
        submit: true,
      },
      {
        expectSubmit: {
          status: 'accepted',
          data: {
            firstName: 'Ada',
            lastName: 'Lovelace',
            company: 'Analytical Engines',
            street: 'Rue de la Gare 1',
            city: 'Lausanne',
            invoiceToCompany: true,
            confirm: true,
          },
        },
      },
    ],
  },
]
