import { parse, referencedPaths } from '@formancy/expressions'
import { modelDataPaths } from '@formancy/spec'
import type { FormSchema, LogicRule } from '@formancy/spec'

/**
 * Rules that read a data path the model does not define.
 *
 * **The problem, measured rather than assumed.** An unknown *root* is already
 * caught: the engine compiles each rule against declarations for the fields that
 * exist, so `gone == "8000"` is `Unknown variable: gone` and publishing refuses
 * it. What gets through is everything deeper, because a member of a `map` is
 * `dyn` — `address.nope` and `item.nope` both type-check, publish, and then
 * evaluate as `null == "Zug"` for the life of an immutable version. A
 * conditionally visible field is simply never shown again, and nothing says so
 * at authoring time, at publish time or at run time.
 *
 * That is also the half that matters most, because a grouped path is exactly
 * where a rename leaves a rule behind: inside a group the data path and the
 * builder's tree path differ.
 *
 * Inside the builder this cannot happen any more: a rename or an unwrap rewrites
 * every rule that names the path
 * ([0093](../../../docs/decisions/0093-a-rule-follows-the-path-it-reads.md)). A
 * document written by hand, generated by a script or composed by an agent has no
 * such help.
 *
 * **This reports; it does not refuse**, and that is the decision rather than a
 * limitation. Making `validateSchema` reject such a document would make
 * documents that are valid today invalid tomorrow, and what a reader accepts is
 * the version contract — which is frozen. So the finding travels as a warning on
 * a *successful* publish
 * ([0097](../../../docs/decisions/0097-a-publish-may-warn.md)).
 *
 * **Why not part of `expressionProblems`.** That asks a type question and its
 * findings refuse the publish. This asks a model question, which the type
 * checker cannot answer past the first segment. Comparing what a rule reads
 * against what the model defines answers it at any depth.
 *
 * The root case is reported here too, even though publishing refuses it before
 * this runs: a caller that is not the publish path — the authoring check, an
 * agent composing a document — wants the whole answer rather than the part
 * another gate happens to cover.
 */
export interface UnknownReference {
  /** The rule's target, as written. */
  target: string
  kind: LogicRule['kind']
  cel: string
  /** The paths it reads that no field provides, sorted, as the model would write them. */
  paths: readonly string[]
  /** What the author has to change, in their words. */
  message: string
}

/**
 * The row variables a rule inside a repeater sees, which are not fields.
 *
 * `item` stands for the row being evaluated, so `item.qty` is the model's
 * `items[].qty` and has to be rewritten before it can be looked up. `index` is a
 * number and names nothing.
 */
const ROW_ITEM = 'item'
const ROW_INDEX = 'index'

/** `items[0].qty` and `items[].qty` are the same field; the model writes the second. */
function withoutRowNumbers(path: string): string {
  return path.replaceAll(/\[\d+\]/g, '[]')
}

export function unknownReferences(schema: FormSchema): UnknownReference[] {
  const rules = schema.logic?.rules ?? []
  if (rules.length === 0) return []

  const defined = new Set(modelDataPaths(schema.model))
  const found: UnknownReference[] = []

  for (const rule of rules) {
    // A check names a validator the deployment answers and carries no
    // expression; whether that name resolves is asked elsewhere, at publish.
    if (rule.cel === undefined || rule.cel === '') continue

    // Parsed with no declarations on purpose: that is enough to ask an
    // expression what it reads, and it keeps this independent of how strictly
    // anything else chooses to declare a field.
    const parsed = parse(rule.cel)
    // A parse failure is fatal at publish already. Reporting it twice, in
    // different words, helps nobody.
    if (!parsed.ok) continue

    /*
     * The repeater a row rule belongs to, so `item.x` can be resolved.
     *
     * Taken from the TARGET rather than guessed: a rule on `items[].total` is
     * evaluated per row of `items`, and that is the only repeater its `item`
     * can mean.
     */
    const rowScope = rule.target.includes('[]')
      ? `${rule.target.slice(0, rule.target.indexOf('[]'))}[]`
      : undefined

    const missing = new Set<string>()
    for (const read of referencedPaths(parsed.ast)) {
      const path = withoutRowNumbers(read)
      if (path === ROW_INDEX) continue

      if (path === ROW_ITEM || path.startsWith(`${ROW_ITEM}.`)) {
        // Outside a repeater `item` is not bound to anything, so it is as
        // unknown as any other name — reported under its own spelling, because
        // there is no row to rewrite it into.
        if (rowScope === undefined) {
          missing.add(path)
          continue
        }
        const resolved = `${rowScope}${path.slice(ROW_ITEM.length)}`
        if (!defined.has(resolved)) missing.add(resolved)
        continue
      }

      if (!defined.has(path)) missing.add(path)
    }

    if (missing.size === 0) continue
    const paths = [...missing].sort()
    found.push({
      target: rule.target,
      kind: rule.kind,
      cel: rule.cel,
      paths,
      message:
        `Rule on "${rule.target}" (${rule.kind}) reads ${paths
          .map((path) => `"${path}"`)
          .join(', ')}, which no field provides. ` +
        `The expression evaluates to nothing, so the rule never does anything — ` +
        `and because an unknown field is allowed to be empty rather than wrong, ` +
        `nothing else will report it.`,
    })
  }

  return found
}
